#linear model with unnormalized dataset:
lm_sssp_u: lm.py
	python lm.py ../datasets/unnormalized_sssp.csv

lm_bfs_u: lm.py
	python lm.py ../datasets/unnormalized_bfs.csv	

lm_tc_u: lm.py
	python lm.py ../datasets/unnormalized_tc.csv

lm_pr_u: lm.py
	python lm.py ../datasets/unnormalized_pr.csv

#linear model with unnormalized dataset:

lm_sssp_n: lm.py
	python lm.py ../datasets/normalized_sssp.csv

lm_bfs_n: lm.py
	python lm.py ../datasets/normalized_bfs.csv	

lm_tc_n: lm.py
	python lm.py ../datasets/normalized_tc.csv

lm_pr_n: lm.py
	python lm.py ../datasets/normalized_pr.csv

#linear model with ridging and unnormalized dataset:

ridge_sssp_u: lm_ridge.py
	python lm_ridge.py ../datasets/unnormalized_sssp.csv

ridge_bfs_u: lm_ridge.py
	python lm_ridge.py ../datasets/unnormalized_bfs.csv

ridge_tc_u: lm_ridge.py
	python lm_ridge.py ../datasets/unnormalized_tc.csv

ridge_pr_u: lm_ridge.py
	python lm_ridge.py ../datasets/unnormalized_pr.csv


#linear model with ridging and normalized dataset:
ridge_sssp_n: lm_ridge.py
	python lm_ridge.py ../datasets/normalized_sssp.csv

ridge_bfs_n: lm_ridge.py
	python lm_ridge.py ../datasets/normalized_bfs.csv

ridge_tc_n: lm_ridge.py
	python lm_ridge.py ../datasets/normalized_tc.csv

ridge_pr_n: lm_ridge.py
	python lm_ridge.py ../datasets/normalized_pr.csv

#Random forest:
rf_sssp:
	python random_forest.py ../datasets/classifier_sssp.csv

rf_bfs:
	python random_forest.py ../datasets/classifier_bfs.csv

rf_tc:
	python random_forest.py ../datasets/classifier_tc.csv

rf_pr:
	python random_forest.py ../datasets/classifier_pr.csv

#Logistic regression:
lr_sssp:
	python logistic.py ../datasets/classifier_sssp.csv

lr_bfs:
	python logistic.py ../datasets/classifier_bfs.csv

lr_tc:
	python logistic.py ../datasets/classifier_tc.csv

lr_pr:
	python logistic.py ../datasets/classifier_pr.csv




